# Generated by Django 4.2.7 on 2023-11-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="SignUpEmailVerifyToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=320, unique=True)),
                ("token", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
