# Generated by Django 4.2.7 on 2023-11-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=20)),
                ("last_update", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserKeyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.CharField(max_length=50)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserStack",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("language", models.CharField(max_length=20)),
                ("code_amount", models.IntegerField()),
            ],
        ),
    ]
