from django.urls import path
from projects import views as project

urlpatterns = [
    path(
        "v1",
        project.Info.as_view(),
        name="project_info",
    ),
    path(
        "v1/<int:project_id>",
        project.Info.as_view(),
        name="project_info_id",
    ),
    path(
        "v1/<int:project_id>/milestone-gpt",
        project.MakeMilestoneByGPT.as_view(),
        name="project_make_milestone_gpt",
    ),
    path(
        "v1/info/<int:project_id>",
        project.PublicInfo.as_view(),
        name="project_info",
    ),
    path(
        "v1/info/all",
        project.AllInfo.as_view(),
        name="project_all_info",
    ),
    path(
        "v1/invite",
        project.Invite.as_view(),
        name="project_invite",
    ),
    path(
        "v1/<int:project_id>/role",
        project.Role.as_view(),
        name="project_role",
    ),
    path(
        "v1/<int:project_id>/kick",
        project.Kick.as_view(),
        name="project_kick",
    ),
    path(
        "v1/recommend",
        project.RecommendProject.as_view(),
        name="project_recommend",
    ),
    path(
        "v1/recommend/<int:project_id>",
        project.RecommendUserForProject.as_view(),
        name="user_recommend_for_project",
    ),
    path(
        "v1/<int:project_id>/join",
        project.MakeJoinRequest.as_view(),
        name="project_join_request",
    ),
    path(
        "v1/join/reply",
        project.ReplyJoinRequest.as_view(),
        name="project_join_request_reply",
    ),
]
