# Generated by Django 4.2.7 on 2023-11-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tags", models.JSONField(blank=True, null=True)),
                ("subject", models.CharField(max_length=100)),
                ("status", models.CharField(default="READY", max_length=20)),
                ("created_at", models.DateTimeField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
