# Generated by Django 4.2.7 on 2023-11-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
