class ReturnCode:
    SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
    PRE_SIGN_UP_SUCCESS = "PRE_SIGN_UP_SUCCESS"
    NO_MATCHING_SOCIAL_TYPE = "NO_MATCHING_SOCIAL_TYPE"
    ERROR_PRE_CREATING_USER = "ERROR_PRE_CREATING_USER"
    INVALID_ACCESS = "INVALID_ACCESS"
    SUCCESS = "SUCCESS"
    FAIL = "FAIL"
    HISTORY_UPDATE_SUCCESS = "HISTORY_UPDATE_SUCCESS"
    NO_GITHUB_URL = "NO_GITHUB_URL"
    CANNOT_FIND_GITHUB_ACCOUNT = "CANNOT_FIND_GITHUB_ACCOUNT"
    GITHUB_STATUS_IN_PROGRESS = "IN_PROGRESS"
    GITHUB_STATUS_COMPLETE = "COMPLETE"
    GITHUB_STATUS_FAILED = "FAILED"
    FAILED_CREATE_PRESIGNED_URL = "FAILED_CREATE_PRESIGNED_URL"


class ReturnList:
    WORD_LIST = [
        "react",
        "node",
        "express",
        "angular",
        "next",
        "recoil",
        "nuxt",
        "enzyme",
        "mocha",
        "karma",
        "sinon",
        "appium",
        "selenium",
        "springboot",
        "liquibase",
        "apollo",
        "koa",
        "netty",
        "nest",
        "grpc",
        "webrtc",
        "mongodb",
        "mysql",
        "elasticsearch",
        "redis",
        "cassandra",
        "memcached",
        "arcus",
        "cubird",
        "solr",
        "neo4j",
        "ceph",
        "zeppelin",
        "hbase",
        "kibana",
        "kafka",
        "druid",
        "grafana",
        "airflow",
        "tensorflow",
        "keras",
        "torch",
        "pytorch",
        "fluentd",
        "zipkin",
        "docker",
        "jenkins",
        "harbor",
        "traefik",
        "ansible",
        "oracledb",
        "retrofit",
        "retrofit2",
        "rocksdb",
        "unity",
        "argo",
        "celery",
        "cockroachdb",
        "flutter",
        "glide",
        "kotest",
        "kudu",
        "looker",
        "lottie",
        "mssql",
        "nexus",
        "action",
        "reactivex",
        "electron",
        "kubernetes",
        "prometheus",
        "puppeteer",
        "junit",
        "firebase",
        "aws",
        "rabbitmq",
        "postgresql",
        "arangodb",
        "greenplum",
        "jest",
        "opengl",
        "storybook",
        "vue",
        "relay",
        "vuex",
        "graphql",
        "redux",
        "django",
        "spring",
        "fastapi",
        "flask",
        "hadoop",
        "spark",
        "flink",
        "hive",
        "storm",
    ]
