# Generated by Django 4.2.7 on 2023-11-21 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_groups", "0001_initial"),
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task_groups.taskgroup"
            ),
        ),
        migrations.DeleteModel(
            name="TaskGroup",
        ),
    ]
