class ReturnCode:
    SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
    PRE_SIGN_UP_SUCCESS = "PRE_SIGN_UP_SUCCESS"
    NO_MATCHING_SOCIAL_TYPE = "NO_MATCHING_SOCIAL_TYPE"
    ERROR_PRE_CREATING_USER = "ERROR_PRE_CREATING_USER"
