# Generated by Django 4.2.7 on 2023-11-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(default="READY", max_length=20)),
                ("title", models.CharField(max_length=50)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_resource_links", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "thumbnail_image",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectInvite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(default="READY", max_length=20)),
                ("title", models.CharField(max_length=50)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_resource_links", models.JSONField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "thumbnail_image",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("role", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
