# Generated by Django 4.2.7 on 2023-11-21 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectinvite",
            name="description",
        ),
        migrations.RemoveField(
            model_name="projectinvite",
            name="description_resource_links",
        ),
        migrations.RemoveField(
            model_name="projectinvite",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="projectinvite",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="projectinvite",
            name="role",
        ),
        migrations.RemoveField(
            model_name="projectinvite",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="projectinvite",
            name="status",
        ),
        migrations.RemoveField(
            model_name="projectinvite",
            name="thumbnail_image",
        ),
        migrations.RemoveField(
            model_name="projectinvite",
            name="title",
        ),
    ]
