# Generated by Django 4.2.7 on 2023-11-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_projectjoinrequest"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="project_user_unique"
            ),
        ),
    ]
