# Generated by Django 4.2.7 on 2023-11-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_ads_delete_adsrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("requester_email", models.CharField(max_length=100)),
                ("requester_name", models.CharField(max_length=10)),
                ("company_email", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=30)),
                ("purpose", models.CharField(max_length=100)),
                ("file_link", models.TextField()),
                ("initial_exposure_count", models.IntegerField(blank=True, null=True)),
                (
                    "remaining_exposure_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Ads",
        ),
    ]
