# Generated by Django 4.2.7 on 2023-12-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_ad_delete_ads"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="site_link",
            field=models.TextField(default=""),
        ),
    ]
