# Generated by Django 4.2.6 on 2023-10-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerifyToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=320, unique=True)),
                ("token", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
