# Generated by Django 4.2.6 on 2023-10-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_link",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
