# Generated by Django 4.2.6 on 2023-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
