# Generated by Django 4.2.6 on 2023-10-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0003_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
