# Generated by Django 4.2.7 on 2023-11-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0004_project_projectmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(default="READY", max_length=20),
        ),
    ]
