# Generated by Django 4.2.6 on 2023-10-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0005_user_has_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pre_access_token",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="provider",
            field=models.CharField(default="our", max_length=20),
        ),
    ]
