# Generated by Django 4.2.6 on 2023-10-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0006_user_pre_access_token_user_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pre_access_token",
            field=models.TextField(null=True),
        ),
    ]
