# Generated by Django 4.2.7 on 2023-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0006_alter_project_owner_alter_projectmember_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="like",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
