# Generated by Django 4.2.7 on 2023-11-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0007_alter_user_grade_alter_user_like_alter_user_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_profile_image",
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
