# Generated by Django 4.2.7 on 2023-11-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0009_userstack_githubstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubstatus",
            name="status",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="userstack",
            name="language",
            field=models.CharField(max_length=20),
        ),
    ]
