# Generated by Django 4.2.7 on 2023-11-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0010_alter_githubstatus_status_alter_userstack_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="S3ResourceReferenceCheck",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("resource_name", models.CharField(max_length=30)),
                ("reference_cnt", models.IntegerField()),
            ],
        ),
    ]
