# Generated by Django 4.2.7 on 2023-11-09 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0010_alter_githubstatus_status_alter_userstack_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description_resource_links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image_link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="S3ResourceReferenceCheck",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("resource_link", models.CharField(max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
