# Generated by Django 4.2.7 on 2023-11-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0011_user_description_resource_links_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_resource_links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.TextField(default=""),
        ),
    ]
