# Generated by Django 4.2.7 on 2023-11-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0011_s3resourcereferencecheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description_resource_links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
