# Generated by Django 4.2.7 on 2023-11-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0012_user_description_resource_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="s3resourcereferencecheck",
            name="resource_name",
        ),
        migrations.AddField(
            model_name="s3resourcereferencecheck",
            name="resource_link",
            field=models.CharField(default="1", max_length=100),
            preserve_default=False,
        ),
    ]
