# Generated by Django 4.2.7 on 2023-11-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0012_project_description_resource_links_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
