# Generated by Django 4.2.7 on 2023-11-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0013_remove_s3resourcereferencecheck_resource_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image_link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
