# Generated by Django 4.2.7 on 2023-11-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0013_alter_project_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="github_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
