# Generated by Django 4.2.7 on 2023-11-13 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0014_alter_user_github_link_alter_user_profile_image_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_public",
        ),
    ]
