# Generated by Django 4.2.7 on 2023-11-14 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0016_milestone_remove_project_is_public_taskgroup_task_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserKeyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
