# Generated by Django 4.2.7 on 2023-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0017_userkeyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="userkeyword",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
