# Generated by Django 4.2.7 on 2023-11-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0019_projectinvite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="like",
        ),
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail_image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
