# Generated by Django 4.2.7 on 2023-11-17 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domo_api", "0020_remove_project_like_project_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="created_by",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
