# Generated by Django 4.2.7 on 2023-12-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("owner", "feed"), name="owner_feed_unique"
            ),
        ),
    ]
