name: '[DOMO] Lint & Test'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black_isort:
    name: Check Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'poetry'
          cache-dependency-path: poetry.lock
          python-version: 3.10.13

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run Black check
        run: poetry run black --diff --check .

      - name: Run isort check
        run: poetry run isort --profile black --skip-glob="**/migrations" --diff --check .

  django_tests:
    name: Run Django test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'poetry'
          cache-dependency-path: poetry.lock
          python-version: 3.10.13

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run Django tests
        working-directory: domo
        env:
          DOMO_DJANGO_SECRET_KEY: 'SECRETKEY-FOR-TEST'
          DOMO_DB_NAME: postgres
          DOMO_DB_USER: postgres
          DOMO_DB_PASSWORD: postgres
          DOMO_DB_HOST: localhost
          DOMO_DB_PORT: 5432
          DJANGO_SETTINGS_MODULE: domo_base.settings.base
        run: |
          poetry run python manage.py makemigrations
          poetry run python manage.py migrate
          poetry run python manage.py test --parallel
